### ISSUE TITLE
Flatfile to MySQL conversion problems

### ISSUE THREAD

**Issue by TheCoolsurdy** [LlmDl/Towny#2652] opened 2017-08-04 00:03 UTC
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. Have Towny in flatfile with hundreds of thousands of townblocks (120,000+)
2. Attempt to convert flatfile to MySQL by following the guide (http://towny.palmergames.com/towny/757-2/#Converting_Flatfile_to_SQL)
3. Once you've started the server with [load] flatfile and [save] mysql, Towny will attempt to convert the files, and once Towny gets to converting the townblocks, it will display several SQL errors, ([Towny] Error: SQL: Save TownBlock unknown error
com.palmergames.bukkit.towny.exceptions.NotRegisteredException: The TownBlock at (world, 286, -113) is not registered to a town.), and as a result, will not transfer any of the townblocks to the MySQL Database

### What is the expected output?
1. Once both [load] and [save] in the config.yml are set to "mysql" the conversion process starts.
2. The conversion process is supposed to work properly and convert all of the files from flatfile to mysql, including all townblocks.

### What is your Towny version?
0.91.2.0

### What is your spigot/craftbukkit version?
Spigot 1.8.8

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log: (WARNING: 330,000 line 28mb .txt file in shitty uncontrollable google drive mode ahead) log was too big for my clipboard & pastebin. for your convenience, the last link is just of the SQL errors, which happen infrequently amongst the 120,000 lines of "Saving townblock") https://drive.google.com/file/d/0B8V3audHu_fsTmxpMnNpQVlxSjA/view
2. Your Towny config.yml (if using MySQL please remove password,) https://pastebin.com/VjAd2yYT:
3. Your townyperms.yml: https://pastebin.com/kwcRtCaa
4. Your log's error: https://pastebin.com/vsq0svaZ

P.S. This is the error that occurs when booting up the server with [load] flatfile and [save] mysql. Once I change [load] to mysql and type /ta reload, Towny attempts to load from the mysql database (which does not have ANY townblocks in the database) and locks into safemode due to the errors in conversion such as this one. Ultimately, what I want the most is to be able to convert my Towny files from flatfile to mysql. Thank you so much!

**Comment by Wolf2323** [comment] 2017-12-13 09:34
my Pull request should solve the problem if its merged :)

**Comment by Wolf2323** [comment] 2018-01-08 09:50
I tried to reproduce this, but i was not able.
So i closed the pull request and i think the issue can be closed.

**Comment by LlmDl** [comment] 2018-01-08 14:16
I'd like to see some of the townblock files that it cannot load. Towny should already be auto-purging townblocks that have no town, even on 0.91.2.0. When wolf2323 set about to fix this issue he was not able to recreate the townblocks because towny would autopurge them one the first load using flatfile.

**Comment by LlmDl** [comment] 2018-01-21 16:07
2+ weeks of inactivity. Closing ticket.

**Closed by LlmDl** 2018-01-21 16:07 UTC
Labels: Label-Data, Need Feedback
