### ISSUE TITLE
Town data not existing in one file/directory causing safe mode lockage, lots of downtime for my server.

### ISSUE THREAD

**Issue by TheCoolsurdy** [LlmDl/Towny#2502] opened 2016-07-18 03:27 UTC
Spigot Version: This server is running CraftBukkit version git-Spigot-6c9b0a1-de5c261 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

Towny: 0.91.1.0

Hello,

For as long as I can remember, Towny has been getting into safe mode. It's no issue usually, very simple and easy to fix the corruption. (By manually deleting the corrupted town/nation). **However, I have noticed one type of corruption that is very easy to fix, occurring quite consistently (at least once every 1-2 months). Usually I am able to fix it within 2 minutes, however when I am out of the house my server can be offline for up to 24 hours if I don't have access to a computer.** I am requesting that we work together to solve this issue. I remember I worked with you, LLmdl, to resolve town block corruption and tipped you $10.

I would greatly appreciate a favor like that, whenever you have the time, to fix this. Of course, I do not know if this is possible from a development standpoint but I'd presume so.

Basically, I'll give you the most recent example.

Here is an excerpt from latest.log:

`[22:59:56] [Server thread/INFO]: [Towny] Debug: World Fetching Town: merchants

[22:59:56] [Server thread/WARN]: [Towny] Error: Loading Error: Exception while reading world file 
plugins/Towny/data/worlds/world.txt

[22:59:56] [Server thread/INFO]: [Towny] Loading Error: Could not read world data 'world'.

[22:59:56] [Server thread/INFO]: [Towny] Error: Failed to load!

[22:59:56] [Server thread/INFO]: 

=============================================================

[22:59:56] [Server thread/INFO]: [WARNING] - ***** SAFE MODE ***** 0.91.1.0

[22:59:56] [Server thread/INFO]: 

=============================================================`

Towny loads all the towns, but stops at 'merchants'. It then has an issue reading /data/worlds/world.txt and locks into safe mode.

This issue was fixed by me adding 'merchants' to the town= part of my world.txt, which took about 30 seconds.

merchants existed in towns.txt, and in /data/towns but not in /data/worlds/world.txt

I  presume World Fetching Town is the first task Towny does to load towns. Possibly listing towns from towns.txt and loading them from world.txt and /towns, or however it works. In this case (I think) Towny read merchants somewhere but could not find it in world.txt and thus had an issue reading the file and locked up.

**My concern is, is there any potiential way we can work to resolve this particular instance of Towny corruption? For example, seeing if the town having issues exists in other areas, such as towns.txt and /data/towns and then rebuilding the town name in world.txt, {or if it is missing in any of the 2 other files, rebuilding it in the appropriate one based off of the 2 others}, or perhaps a more extreme method such as deleting the town having issues?**

**Comment by LlmDl** [comment] 2016-07-18 03:30
In order to figure this out we need you to figure out how the town was removed from that world.txt. 

Is that town one that changed its town spawn's world? Was teh town ever manually deleted, or non-manually deleted? What do you know about the towns this happens to?

**Comment by TheCoolsurdy** [comment] 2016-07-18 03:37
This town was a very new town, I believe it was created the same day Towny crashed. My server has 2 scheduled restarts daily, one at 2AM and one at 2PM EST. The restarts are through Multicraft, and it properly restarts by saving the world, shutting down the server completely, and then starting up the server again. I'm sure you're familiar with the way Multicraft works. **I've noticed all the towns this happens to are also very new as well.**

Anyways, when the server loads up again, Towny has the issue and it locks up. I presume, is it possible the town was never added to world.txt? The town only existed in world, it did not change its spawn location, never deleted or manually deleted.

There is one other type of corruption where the town is deleted via the disband command from the mayor, and the town deletes in some places but never deletes in other places.

**Comment by TheCoolsurdy** [comment] 2016-07-22 00:45
I'll presume you're busy or unable to access the computer at the moment. Please contact me as soon as you can. Thanks so much

BTW, my server crashed and I believe it is Towny:

`21.07 20:16:43 [Server] ERROR ------------------------------
21.07 20:16:43 [Server] ERROR java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)
21.07 20:16:43 [Server] ERROR java.lang.ref.Reference.tryHandlePending(Reference.java:191)
21.07 20:16:43 [Server] ERROR java.lang.Object.wait(Object.java:502)
21.07 20:16:43 [Server] ERROR java.lang.Object.wait(Native Method)
21.07 20:16:43 [Server] ERROR Stack:
21.07 20:16:43 [Server] ERROR PID: 2 | Suspended: false | Native: false | State: WAITING
21.07 20:16:43 [Server] ERROR Current Thread: Reference Handler
21.07 20:16:43 [Server] ERROR ------------------------------
21.07 20:16:43 [Server] ERROR java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)
21.07 20:16:43 [Server] ERROR java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
21.07 20:16:43 [Server] ERROR java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
21.07 20:16:43 [Server] ERROR java.lang.Object.wait(Native Method)
21.07 20:16:43 [Server] ERROR Stack:
21.07 20:16:43 [Server] ERROR PID: 3 | Suspended: false | Native: false | State: WAITING
21.07 20:16:43 [Server] ERROR Current Thread: Finalizer
21.07 20:16:43 [Server] ERROR ------------------------------
21.07 20:16:43 [Server] ERROR Stack:
21.07 20:16:43 [Server] ERROR PID: 5 | Suspended: false | Native: false | State: RUNNABLE
21.07 20:16:43 [Server] ERROR Current Thread: Signal Dispatcher
21.07 20:16:43 [Server] ERROR ------------------------------
21.07 20:16:43 [Server] ERROR java.util.TimerThread.run(Timer.java:505)
21.07 20:16:43 [Server] ERROR java.util.TimerThread.mainLoop(Timer.java:552)
21.07 20:16:43 [Server] ERROR java.lang.Object.wait(Native Method)
21.07 20:16:43 [Server] ERROR Stack:
21.07 20:16:43 [Server] ERROR PID: 13 | Suspended: false | Native: false | State: TIMED_WAITING
21.07 20:16:43 [Server] ERROR Current Thread: Snooper Timer
21.07 20:16:43 [Server] ERROR ------------------------------
21.07 20:16:43 [Server] ERROR net.minecraft.server.v1_8_R3.DedicatedServer$1.run(DedicatedServer.java:54)
21.07 20:16:43 [Server] ERROR java.lang.Thread.sleep(Native Method)
21.07 20:16:43 [Server] ERROR Stack:
21.07 20:16:43 [Server] ERROR PID: 17 | Suspended: false | Native: false | State: TIMED_WAITING
21.07 20:16:43 [Server] ERROR Current Thread: Server Infinisleeper
21.07 20:16:43 [Server] ERROR ------------------------------
21.07 20:16:43 [Server] ERROR java.lang.Thread.run(Thread.java:745)
21.07 20:16:43 [Server] ERROR net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556)
21.07 20:16:43 [Server] ERROR net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653)
21.07 20:16:43 [Server] ERROR net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
21.07 20:16:43 [Server] ERROR net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:722)
21.07 20:16:43 [Server] ERROR org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
21.07 20:16:43 [Server] ERROR org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
21.07 20:16:43 [Server] ERROR com.palmergames.bukkit.towny.command.TownCommand$2.run(TownCommand.java:1590)
21.07 20:16:43 [Server] ERROR com.palmergames.bukkit.towny.db.TownyDatabaseHandler.removeTown(TownyDatabaseHandler.java:435)
21.07 20:16:43 [Server] ERROR com.palmergames.bukkit.towny.db.TownyDatabaseHandler.removeTownBlocks(TownyDatabaseHandler.java:287)
21.07 20:16:43 [Server] ERROR com.palmergames.bukkit.towny.db.TownyDatabaseHandler.removeTownBlock(TownyDatabaseHandler.java:262)
21.07 20:16:43 [Server] ERROR com.palmergames.bukkit.towny.db.TownyFlatFileSource.saveTownBlockList(TownyFlatFileSource.java:1454)
21.07 20:16:43 [Server] ERROR Stack:
21.07 20:16:43 [Server] ERROR PID: 16 | Suspended: false | Native: false | State: RUNNABLE
21.07 20:16:43 [Server] ERROR Current Thread: Server thread
21.07 20:16:43 [Server] ERROR ------------------------------
21.07 20:16:43 [Server] ERROR Stack:
21.07 20:16:43 [Server] ERROR PID: 18 | Suspended: false | Native: false | State: RUNNABLE
21.07 20:16:43 [Server] ERROR Current Thread: DestroyJavaVM
21.07 20:16:43 [Server] ERROR ------------------------------
21.07 20:16:43 [Server] ERROR java.lang.Thread.run(Thread.java:745)
21.07 20:16:43 [Server] ERROR org.bukkit.craftbukkit.v1_8_R3.util.TerminalConsoleWriterThread.run(TerminalConsoleWriterThread.java:25)
21.07 20:16:43 [Server] ERROR com.mojang.util.QueueLogAppender.getNextLogEvent(QueueLogAppender.java:77)
21.07 20:16:43 [Server] ERROR java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
21.07 20:16:43 [Server] ERROR java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
21.07 20:16:43 [Server] ERROR java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
21.07 20:16:43 [Server] ERROR sun.misc.Unsafe.park(Native Method)
21.07 20:16:43 [Server] ERROR Stack:
21.07 20:16:43 [Server] ERROR PID: 20 | Suspended: false | Native: false | State: WAITING
21.07 20:16:43 [Server] ERROR Current Thread: Thread-4
21.07 20:16:43 [Server] ERROR ------------------------------
21.07 20:16:43 [Server] ERROR net.minecraft.server.v1_8_R3.DedicatedServer$2.run(DedicatedServer.java:81)
21.07 20:16:43 [Server] ERROR org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readLine(ConsoleReader.java:2257)
21.07 20:16:43 [Server] ERROR org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readLine(ConsoleReader.java:2269)
21.07 20:16:43 [Server] ERROR java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
21.07 20:16:43 [Server] ERROR java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
21.07 20:16:43 [Server] ERROR java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
21.07 20:16:43 [Server] ERROR java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
21.07 20:16:43 [Server] ERROR sun.misc.Unsafe.park(Native Method)
21.07 20:16:43 [Server] ERROR Stack:
21.07 20:16:43 [Server] ERROR PID: 155 | Suspended: false | Native: false | State: WAITING
21.07 20:16:43 [Server] ERROR Current Thread: pool-42-thread-1
21.07 20:16:43 [Server] ERROR ------------------------------
21.07 20:16:43 [Server] ERROR java.lang.Thread.run(Thread.java:745)
21.07 20:16:43 [Server] ERROR java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
21.07 20:16:43 [Server] ERROR java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
21.07 20:16:43 [Server] ERROR java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
21.07 20:16:43 [Server] ERROR java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
21.07 20:16:43 [Server] ERROR java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
21.07 20:16:43 [Server] ERROR java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
21.07 20:16:43 [Server] ERROR sun.misc.Unsafe.park(Native Method)
21.07 20:16:43 [Server] ERROR Stack:
21.07 20:16:43 [Server] ERROR PID: 195 | Suspended: false | Native: false | State: WAITING
21.07 20:16:43 [Server] ERROR Current Thread: Head Conversion Thread - 0
21.07 20:16:43 [Server] ERROR ------------------------------
21.07 20:16:43 [Server] ERROR java.lang.Thread.run(Thread.java:745)
21.07 20:16:43 [Server] ERROR java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
21.07 20:16:43 [Server] ERROR java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
21.07 20:16:43 [Server] ERROR java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
21.07 20:16:43 [Server] ERROR java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
21.07 20:16:43 [Server] ERROR java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
21.07 20:16:43 [Server] ERROR java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
21.07 20:16:43 [Server] ERROR sun.misc.Unsafe.park(Native Method)
21.07 20:16:43 [Server] ERROR Stack:
21.07 20:16:43 [Server] ERROR PID: 196 | Suspended: false | Native: false | State: WAITING
21.07 20:16:43 [Server] ERROR Current Thread: Head Conversion Thread - 1
21.07 20:16:43 [Server] ERROR ------------------------------
21.07 20:16:43 [Server] ERROR java.lang.Thread.run(Thread.java:745)
21.07 20:16:43 [Server] ERROR java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
21.07 20:16:43 [Server] ERROR java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
21.07 20:16:43 [Server] ERROR java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
21.07 20:16:43 [Server] ERROR java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
21.07 20:16:43 [Server] ERROR java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
21.07 20:16:43 [Server] ERROR java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
21.07 20:16:43 [Server] ERROR sun.misc.Unsafe.park(Native Method)
21.07 20:16:43 [Server] ERROR Stack:
21.07 20:16:43 [Server] ERROR PID: 197 | Suspended: false | Native: false | State: WAITING
21.07 20:16:43 [Server] ERROR Current Thread: Head Conversion Thread - 2
21.07 20:16:43 [Server] ERROR ------------------------------
21.07 20:16:43 [Server] ERROR java.lang.Thread.run(Thread.java:745)
21.07 20:16:43 [Server] ERROR sun.net.www.http.KeepAliveStreamCleaner.run(KeepAliveStreamCleaner.java:101)
21.07 20:16:43 [Server] ERROR java.lang.Object.wait(Native Method)
21.07 20:16:43 [Server] ERROR Stack:
21.07 20:16:43 [Server] ERROR PID: 230 | Suspended: false | Native: false | State: WAITING
21.07 20:16:43 [Server] ERROR Current Thread: Keep-Alive-SocketCleaner
21.07 20:16:43 [Server] ERROR ------------------------------
21.07 20:16:43 [Server] ERROR java.lang.Thread.run(Thread.java:745)
21.07 20:16:43 [Server] ERROR java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
21.07 20:16:43 [Server] ERROR java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
21.07 20:16:43 [Server] ERROR java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
21.07 20:16:43 [Server] ERROR java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
21.07 20:16:43 [Server] ERROR java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
21.07 20:16:43 [Server] ERROR java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
21.07 20:16:43 [Server] ERROR sun.misc.Unsafe.park(Native Method)
21.07 20:16:43 [Server] ERROR Stack:
21.07 20:16:43 [Server] ERROR PID: 348 | Suspended: false | Native: false | State: WAITING
21.07 20:16:43 [Server] ERROR Current Thread: bugsnag-notification-worker
21.07 20:16:43 [Server] ERROR ------------------------------
21.07 20:16:43 [Server] ERROR java.lang.Thread.run(Thread.java:745)
21.07 20:16:43 [Server] ERROR java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
21.07 20:16:43 [Server] ERROR java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
21.07 20:16:43 [Server] ERROR java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
21.07 20:16:43 [Server] ERROR java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
21.07 20:16:43 [Server] ERROR java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
21.07 20:16:43 [Server] ERROR java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
21.07 20:16:43 [Server] ERROR sun.misc.Unsafe.park(Native Method)
21.07 20:16:43 [Server] ERROR Stack:
21.07 20:16:43 [Server] ERROR PID: 350 | Suspended: false | Native: false | State: WAITING
21.07 20:16:43 [Server] ERROR Current Thread: bugsnag-notification-worker
21.07 20:16:43 [Server] ERROR ------------------------------
21.07 20:16:43 [Server] ERROR java.lang.Thread.run(Thread.java:745)
21.07 20:16:43 [Server] ERROR java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
21.07 20:16:43 [Server] ERROR java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
21.07 20:16:43 [Server] ERROR net.buycraft.plugin.internal.okhttp3.ConnectionPool$1.run(ConnectionPool.java:65)
21.07 20:16:43 [Server] ERROR java.lang.Object.wait(Object.java:460)
21.07 20:16:43 [Server] ERROR java.lang.Object.wait(Native Method)
21.07 20:16:43 [Server] ERROR Stack:
21.07 20:16:43 [Server] ERROR PID: 388 | Suspended: false | Native: false | State: TIMED_WAITING
21.07 20:16:43 [Server] ERROR Current Thread: OkHttp ConnectionPool
21.07 20:16:43 [Server] ERROR ------------------------------
21.07 20:16:43 [Server] ERROR java.util.TimerThread.run(Timer.java:505)
21.07 20:16:43 [Server] ERROR java.util.TimerThread.mainLoop(Timer.java:526)
21.07 20:16:43 [Server] ERROR java.lang.Object.wait(Object.java:502)
21.07 20:16:43 [Server] ERROR java.lang.Object.wait(Native Method)
21.07 20:16:43 [Server] ERROR Stack:
21.07 20:16:43 [Server] ERROR PID: 2138 | Suspended: false | Native: false | State: WAITING
21.07 20:16:43 [Server] ERROR Current Thread: Timer-9
21.07 20:16:43 [Server] ERROR ------------------------------
21.07 20:16:43 [Server] ERROR java.lang.Thread.run(Thread.java:745)
21.07 20:16:43 [Server] ERROR java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
21.07 20:16:43 [Server] ERROR java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
21.07 20:16:43 [Server] ERROR java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1066)
21.07 20:16:43 [Server] ERROR java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941)
21.07 20:16:43 [Server] ERROR java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
21.07 20:16:43 [Server] ERROR java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460)
21.07 20:16:43 [Server] ERROR java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
21.07 20:16:43 [Server] ERROR sun.misc.Unsafe.park(Native Method)
21.07 20:16:43 [Server] ERROR Stack:
21.07 20:16:43 [Server] ERROR PID: 2208 | Suspended: false | Native: false | State: TIMED_WAITING
21.07 20:16:43 [Server] ERROR Current Thread: Craft Scheduler Thread - 797
21.07 20:16:43 [Server] ERROR ------------------------------
21.07 20:16:43 [Server] ERROR java.lang.Thread.run(Thread.java:745)
21.07 20:16:43 [Server] ERROR java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
21.07 20:16:43 [Server] ERROR java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
21.07 20:16:43 [Server] ERROR java.util.concurrent.FutureTask.run(FutureTask.java:266)
21.07 20:16:43 [Server] ERROR java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
21.07 20:16:43 [Server] ERROR net.minecraft.server.v1_8_R3.PacketPlayInChat$1.run(PacketPlayInChat.java:39)
21.07 20:16:43 [Server] ERROR PID: 2538 | Suspended: false | Native: false | State: RUNNABLE
21.07 20:16:43 [Server] ERROR Current Thread: Async Chat Thread - #46
21.07 20:16:43 [Server] ERROR ------------------------------
21.07 20:16:42 [Server] ERROR Entire Thread Dump:
21.07 20:16:42 [Server] ERROR ------------------------------
21.07 20:16:42 [Server] ERROR java.lang.Thread.run(Thread.java:745)
21.07 20:16:42 [Server] ERROR net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556)
21.07 20:16:42 [Server] ERROR net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653)
21.07 20:16:42 [Server] ERROR net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
21.07 20:16:42 [Server] ERROR net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:722)
21.07 20:16:42 [Server] ERROR org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
21.07 20:16:42 [Server] ERROR org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
21.07 20:16:42 [Server] ERROR com.palmergames.bukkit.towny.command.TownCommand$2.run(TownCommand.java:1590)
21.07 20:16:42 [Server] ERROR com.palmergames.bukkit.towny.db.TownyDatabaseHandler.removeTown(TownyDatabaseHandler.java:435)
21.07 20:16:42 [Server] ERROR com.palmergames.bukkit.towny.db.TownyDatabaseHandler.removeTownBlocks(TownyDatabaseHandler.java:287)
21.07 20:16:42 [Server] ERROR com.palmergames.bukkit.towny.db.TownyDatabaseHandler.removeTownBlock(TownyDatabaseHandler.java:262)
21.07 20:16:42 [Server] ERROR com.palmergames.bukkit.towny.db.TownyFlatFileSource.saveTownBlockList(TownyFlatFileSource.java:1452)
21.07 20:16:42 [Server] ERROR com.palmergames.bukkit.towny.db.TownyDatabaseHandler.getAllTownBlocks(TownyDatabaseHandler.java:295)
21.07 20:16:42 [Server] ERROR java.util.ArrayList.addAll(ArrayList.java:577)
21.07 20:16:42 [Server] ERROR java.util.Collections$SynchronizedCollection.toArray(Collections.java:2024)
21.07 20:16:42 [Server] ERROR java.util.AbstractCollection.toArray(AbstractCollection.java:141)
21.07 20:16:42 [Server] ERROR Stack:
21.07 20:16:42 [Server] ERROR PID: 16 | Suspended: false | Native: false | State: RUNNABLE
21.07 20:16:42 [Server] ERROR Current Thread: Server thread
21.07 20:16:42 [Server] ERROR ------------------------------
21.07 20:16:42 [Server] ERROR Server thread dump (Look for plugins here before reporting to Spigot!):
21.07 20:16:42 [Server] ERROR ------------------------------
21.07 20:16:42 [Server] ERROR Spigot version: git-Spigot-6c9b0a1-de5c261 (MC: 1.8.8)
21.07 20:16:42 [Server] ERROR Be sure to include ALL relevant console errors and Minecraft crash reports
21.07 20:16:42 [Server] ERROR Please report this to http://www.spigotmc.org/
`

**Comment by LlmDl** [comment] 2016-07-22 14:03
That's unreadable, use a pastebin.com link, show me the entire crash report.

**Comment by ThemInspectors** [comment] 2016-07-23 00:38
maybe switch over to SQL? it usually doesn't corrupt

**Comment by andrewyunt** [comment] 2016-07-23 00:47
He means he wants a stack trace (the exceptions generated in the logs) when the server crashes. Those messages you posted above tell us almost nothing about what happened.

**Comment by TheCoolsurdy** [comment] 2016-07-26 06:11
Alright the crash report is fixed, anyways LLmDl, could you work with me to fix this common error of corruption? I could pay you for it like last time and I think it would benefit the Towny community.

**Comment by TheCoolsurdy** [comment] 2016-07-30 05:02
I can't use MySQL since there is no easy way to setup a daily backup without using external programs (I use a Minecraft host, not VPS or Dedi)

Anyways, this shouldn't be too hard to make a fix for, correct?

**Comment by ThemInspectors** [comment] 2016-07-30 15:51
use SQLite it's free, no installation required and not readable

**Comment by Portanna** [comment] 2016-08-09 14:07
I figured out what the corruption error is about and I'm posting some ways to fix in this thread: https://github.com/LlmDl/Towny/issues/2506

**Comment by TheCoolsurdy** [comment] 2016-08-14 15:45
Alright, at this point all I'm asking for is a feature that STOPS the server on safe mode. If the server is in safe mode and players login they start glitching and dying, which means its only more problems as I have to compensate people for their lost items

**Comment by LlmDl** [comment] 2016-08-14 18:29
You skipped the form entirely, which usually means I close the ticket right away. Now I'm re-reading things and I'd have less questions for you if the form had been filled out properly.

You also haven't posted the crash report I asked for. I'm closing this ticket, I want a new ticket made with the form filled out properly, crash report included as well.

**Closed by LlmDl** 2016-08-14 18:29 UTC

**Comment by LlmDl** [comment] 2016-08-14 18:45
Just as an aside, I could not reproduce this. I created 2 new towns in 2 different worlds on separate tests. The first one I hard-stopped teh server to simulate a crash. The second time I shut down teh server like normal. Both times the town was properly added to their corresponding world. Unless you can show me the steps that your example towns took during their short lives I don't think can be reproduced.
