### ISSUE TITLE
Suggestion: More strings added to the language files.

### ISSUE THREAD

**Issue by HollishKid** [LlmDl/Towny#2513] opened 2016-08-23 13:15 UTC
Hello,

I have translated everystring manually in the english.yml.
Nevertheless, there are still quite some strings in english.

Could you add these strings to the english.yml for us to translate them?

Thanks for considering!

**Comment by LlmDl** [comment] 2016-08-23 20:13
Yes, that's something i'd love to do some day, part of the problem is there's no list of what's not translated.

Also, if you've made a new translation file, would you care to share it so that your work can be added to towny?

**Comment by HollishKid** [comment] 2016-09-08 16:34
I would love to share the file, only thing is, I threw stuff in there that is very specific to the server I translated it for.
Would it help if I got you a list of what is and what is not translated(able) ?

**Comment by LlmDl** [comment] 2016-09-08 18:00
Yes that would be helpful.

**Comment by HollishKid** [comment] 2016-09-10 00:24
The main thing I'm thinking of is everything that is informational and printed to the chat.
I mean the outputs of the commands /resident /town and /nation .

I'll add things progressively when I find them.

**Comment by LlmDl** [comment] 2017-06-03 16:51
0.91.4.7 contains a ton more translatable messages (55 more) than before. Closing this ticket. If someone tracks down more untranslateable messages they can start a ticket with a real list of messages.

**Closed by LlmDl** 2017-06-03 16:51 UTC
