### ISSUE TITLE
Mobs spawn in towns when they are toggled off

### ISSUE THREAD

**Issue by Ice2496** [LlmDl/Towny#2541] opened 2017-01-13 21:37 UTC
Our server has currently updated to 1.11.2 and when I joined the Towny server to see how the update was, mobs were spawning all over the town even though they are toggled off.

### What is your Towny version?
dev build 1.8.4

### What is your spigot/craftbukkit version?
0.91.1.7

**Comment by LlmDl** [comment] 2017-01-13 21:39
You skipped the form so I'm going to close this ticket. This problem is usually caused by not using a Citizens meant for the version of MC you're using.

**Closed by LlmDl** 2017-01-13 21:39 UTC

**Comment by Ice2496** [comment] 2017-01-13 21:45
Is citizens required because we were forced to get rid of it

**Comment by LlmDl** [comment] 2017-01-13 21:46
No it's not required. Using a version of citizens that is made for an older version of MC is why you would be having this problem.

**Comment by Ice2496** [comment] 2017-01-13 21:48
There are also no errors showing at all so I couldn't put it above

**Comment by Ice2496** [comment] 2017-01-13 21:48
can you confirm that the mobs don't spawn in towns on your world with the latest build?

**Comment by LlmDl** [comment] 2017-01-13 21:49
I can't help you, start a new ticket and don't skip the form.
